FROM selenium/node-chrome:latest as automationSuite

# Need root access to install nodejs
USER root

# Install Nodejs
RUN apt-get install -y curl \
  && curl -sL https://deb.nodesource.com/setup_9.x | bash - \
  && apt-get install -y nodejs \
  && curl -L https://www.npmjs.com/install.sh | sh

# Copy automation scripts
COPY ./automation/ /tmp/app/
WORKDIR /tmp/app/
RUN cat /etc/hosts

# Configure and Run Automation Suite
RUN npm install
RUN npm run cmod_xmlreport || echo "There were failing tests!"
