FROM openjdk:latest as automationSuite

RUN apt-get install -y curl \
  && curl -sL https://deb.nodesource.com/setup_9.x | bash - \
  && apt-get install -y nodejs \
  && curl -L https://www.npmjs.com/install.sh | sh
RUN npm install -g grunt grunt-cli

COPY ./automation /tmp/app
WORKDIR /tmp/app
RUN npm install
RUN npm run cmod_htmlreport
