FROM node:8-alpine as automationSuite
COPY ./automation /tmp/app
USER root
RUN set -o pipefail && apt-get update && apt-get install -y software-properties-common python-software-properties maven && add-apt-repository -y ppa:webupd8team/java && echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections && apt-get update && apt-get install -y oracle-java8-installer
WORKDIR /tmp/app
RUN set -o pipefail && npm install
RUN set -o pipefail && npm run cmod_htmlreport
