const RESET_DATA = 'app/tasks-and-checklist/RESET_DATA';
const GET_CHECKLIST_SAGA = 'app/tasks-and-checklist/GET_CHECKLIST_SAGA';
const GET_NEXT_CHECKLIST = 'app/tasks-and-checklist/GET_NEXT_CHECKLIST';
const GET_PREV_CHECKLIST = 'app/tasks-and-checklist/GET_PREV_CHECKLIST';
const GET_TASKS_SAGA = 'app/tasks-and-checklist/GET_TASKS_SAGA';
const ERROR_LOADING_CHECKLIST = 'app/tasks-and-checklist/ERROR_LOADING_CHECKLIST';
const ERROR_LOADING_TASKS = 'app/tasks-and-checklist/ERROR_LOADING_TASKS';
const HANDLE_CHECKLIST_ITEM_CHANGE = 'app/tasks-and-checklist/HANDLE_CHECKLIST_ITEM_CHANGE';
const LOADING_CHECKLIST = 'app/tasks-and-checklist/LOADING_CHECKLIST';
const LOADING_TASKS = 'app/tasks-and-checklist/LOADING_TASKS';
const REMOVE_DIRTY_CHECKLIST = 'app/tasks-and-checklist/REMOVE_DIRTY_CHECKLIST';
const SET_SELECTED_CHECKLIST = 'app/tasks-and-checklist/SET_SELECTED_CHECKLIST';
const STORE_CHECKLIST = 'app/tasks-and-checklist/STORE_CHECKLIST';
const STORE_TASK_FILTER = 'app/tasks-and-checklist/STORE_TASK_FILTER';
const STORE_CHECKLIST_NAVIGATION = 'app/tasks-and-checklist/STORE_CHECKLIST_NAVIGATION';
const STORE_CHECKLIST_ITEM_CHANGE = 'app/tasks-and-checklist/STORE_CHECKLIST_ITEM_CHANGE';
const STORE_PROCESS_DETAILS = 'app/tasks-and-checklist/STORE_PROCESS_DETAILS';
const STORE_TASKS = 'app/tasks-and-checklist/STORE_TASKS';
const STORE_MISC_TASK_COMMENT = 'app/tasks-and-checklist/STORE_MISC_TASK_COMMENT';
const TOGGLE_INSTRUCTIONS = 'app/tasks-and-checklist/TOGGLE_INSTRUCTIONS';

export {
  GET_NEXT_CHECKLIST,
  GET_PREV_CHECKLIST,
  GET_CHECKLIST_SAGA,
  GET_TASKS_SAGA,
  ERROR_LOADING_CHECKLIST,
  ERROR_LOADING_TASKS,
  HANDLE_CHECKLIST_ITEM_CHANGE,
  LOADING_CHECKLIST,
  LOADING_TASKS,
  REMOVE_DIRTY_CHECKLIST,
  SET_SELECTED_CHECKLIST,
  RESET_DATA,
  STORE_CHECKLIST,
  STORE_CHECKLIST_NAVIGATION,
  STORE_CHECKLIST_ITEM_CHANGE,
  STORE_PROCESS_DETAILS,
  STORE_TASKS,
  STORE_TASK_FILTER,
  STORE_MISC_TASK_COMMENT,
  TOGGLE_INSTRUCTIONS,
};
