const FETCH_TOMBSTONE_DATA = 'app/tombstone/FETCH_TOMBSTONE_DATA';
const LOADING_TOMBSTONE_DATA = 'app/tombstone/LOADING_TOMBSTONE_DATA';
const ERROR_LOADING_TOMBSTONE_DATA = 'app/tombstone/ERROR_LOADING_TOMBSTONE_DATA';
const SUCCESS_LOADING_TOMBSTONE_DATA = 'app/tombstone/SUCCESS_LOADING_TOMBSTONE_DATA';

export {
  FETCH_TOMBSTONE_DATA,
  LOADING_TOMBSTONE_DATA,
  ERROR_LOADING_TOMBSTONE_DATA,
  SUCCESS_LOADING_TOMBSTONE_DATA,
};
