const FETCHCONFIG = 'app/config/FETCHCONFIG';
const FETCHCONFIG_SAGA = 'app/config/FETCHCONFIG_SAGA';
const POWER_BI_CONSTANTS = 'app/config/POWER_BI_CONSTANTS';
const POWER_BI_CONSTANTS_SUCCESS = 'app/config/POWER_BI_CONSTANTS_SUCCESS';
const POWER_BI_CONSTANTS_FAILURE = 'app/config/POWER_BI_CONSTANTS_FAILURE';
const POWER_BI_CONSTANTS_SAGA = 'app/config/POWER_BI_CONSTANTS_SAGA';
const GET_FEATURES_SAGA = 'app/config/GET_FEATURES_SAGA';
const SET_FEATURES = 'app/config/SET_FEATURES';

export {
  FETCHCONFIG,
  FETCHCONFIG_SAGA,
  POWER_BI_CONSTANTS,
  POWER_BI_CONSTANTS_FAILURE,
  POWER_BI_CONSTANTS_SAGA,
  POWER_BI_CONSTANTS_SUCCESS,
  GET_FEATURES_SAGA,
  SET_FEATURES,
};
