const FETCH_TOMBSTONE_DATA = 'app/indexer/FETCH_TOMBSTONE_DATA';
const RESET_DATA = 'app/indexer/RESET_DATA';
const UPDATE_EVAL_LSAMSDETAILS = 'app/indexer/UPDATE_EVAL_LSAMSDETAILS';
const FETCH_GRID_DATA = 'app/indexer/FETCH_GRID_DATA';
const SET_INDEXER_GRID_DATA = 'app/indexer/SET_INDEXER_GRID_DATA';

export {
  RESET_DATA,
  FETCH_TOMBSTONE_DATA,
  UPDATE_EVAL_LSAMSDETAILS,
  FETCH_GRID_DATA,
  SET_INDEXER_GRID_DATA,
};
