const GET_DASHBOARD_COUNTS_SAGA = 'app/stager/GET_DASHBOARD_COUNTS_SAGA';
const SET_STAGER_DATA_COUNTS = 'app/stager/SET_STAGER_DATA_COUNTS';
const GET_DASHBOARD_DATA_SAGA = 'app/stager/GET_DASHBOARD_DATA_SAGA';
const SET_STAGER_DATA = 'app/stager/SET_STAGER_DATA';
const SET_STAGER_DATA_LOADING = 'app/stager/SET_STAGER_DATA_LOADING';
const TABLE_CHECKBOX_SELECT = 'app/stager/TABLE_CHECKBOX_SELECT';
const TABLE_CHECKBOX_SELECT_TRIGGER = 'app/stager/TABLE_CHECKBOX_SELECT_TRIGGER';
const TRIGGER_ORDER_SAGA = 'app/stager/TRIGGER_ORDER_SAGA';
const SET_STAGER_ACTIVE_SEARCH_TERM = 'app/stager/SET_STAGER_ACTIVE_SEARCH_TERM';
const SET_STAGER_DOWNLOAD_CSV_URI = 'app/stager/SET_STAGER_DOWNLOAD_CSV_URI';

export {
  GET_DASHBOARD_COUNTS_SAGA,
  SET_STAGER_DATA_COUNTS,
  GET_DASHBOARD_DATA_SAGA,
  SET_STAGER_DATA,
  SET_STAGER_DATA_LOADING,
  TABLE_CHECKBOX_SELECT,
  TABLE_CHECKBOX_SELECT_TRIGGER,
  TRIGGER_ORDER_SAGA,
  SET_STAGER_DOWNLOAD_CSV_URI,
  SET_STAGER_ACTIVE_SEARCH_TERM,
};
