const GET_DASHBOARD_COUNTS_SAGA = 'app/stager/GET_DASHBOARD_COUNTS_SAGA';
const SET_STAGER_DATA_COUNTS = 'app/stager/SET_STAGER_DATA_COUNTS';
const GET_DASHBOARD_DATA_SAGA = 'app/stager/GET_DASHBOARD_DATA_SAGA';
const SET_STAGER_DATA = 'app/stager/SET_STAGER_DATA';

export {
  GET_DASHBOARD_COUNTS_SAGA,
  SET_STAGER_DATA_COUNTS,
  GET_DASHBOARD_DATA_SAGA,
  SET_STAGER_DATA,
};
