const GET_DASHBOARD_COUNTS_SAGA = 'app/stager/GET_DASHBOARD_COUNTS_SAGA';
const SET_STAGER_DATA_COUNTS = 'app/stager/SET_STAGER_DATA_COUNTS';
const GET_DASHBOARD_DATA_SAGA = 'app/stager/GET_DASHBOARD_DATA_SAGA';
const SET_STAGER_DATA = 'app/stager/SET_STAGER_DATA';
const SET_STAGER_DATA_LOADING = 'app/stager/SET_STAGER_DATA_LOADING';
const TABLE_CHECKBOX_SELECT = 'app/stager/TABLE_CHECKBOX_SELECT';
const TABLE_CHECKBOX_SELECT_TRIGGER = 'app/stager/TABLE_CHECKBOX_SELECT_TRIGGER';
const TRIGGER_ORDER_SAGA = 'app/stager/TRIGGER_ORDER_SAGA';
const TRIGGER_DISPOSITION_OPERATION_SAGA = 'app/stager/TRIGGER_DISPOSITION_OPERATION_SAGA';
const SET_STAGER_ACTIVE_SEARCH_TERM = 'app/stager/SET_STAGER_ACTIVE_SEARCH_TERM';
const SET_STAGER_DOWNLOAD_CSV_URI = 'app/stager/SET_STAGER_DOWNLOAD_CSV_URI';
const SET_DOCS_OUT_RESPONSE = 'app/stager/SET_DOCS_OUT_RESPONSE';
const SET_DOCS_OUT_ACTION = 'app/stager/SET_DOCS_OUT_ACTION';
const CLEAR_DOCS_OUT_RESPONSE = 'app/stager/CLEAR_DOCS_OUT_RESPONSE';
const SET_STAGER_VALUE = 'app/stager/SET_STAGER_VALUE';
const SET_START_END_DATE = 'app/stager/SET_START_END_DATE';


export {
  GET_DASHBOARD_COUNTS_SAGA,
  SET_STAGER_DATA_COUNTS,
  GET_DASHBOARD_DATA_SAGA,
  SET_STAGER_DATA,
  SET_STAGER_DATA_LOADING,
  TABLE_CHECKBOX_SELECT,
  TABLE_CHECKBOX_SELECT_TRIGGER,
  TRIGGER_ORDER_SAGA,
  TRIGGER_DISPOSITION_OPERATION_SAGA,
  SET_STAGER_DOWNLOAD_CSV_URI,
  SET_STAGER_ACTIVE_SEARCH_TERM,
  SET_DOCS_OUT_RESPONSE,
  SET_DOCS_OUT_ACTION,
  CLEAR_DOCS_OUT_RESPONSE,
  SET_STAGER_VALUE,
  SET_START_END_DATE,
};
