const GET_COMMENTS_SAGA = 'app/comments/GET_COMMENTS_SAGA';
const GET_COMMENTS_RESULT = 'app/comments/GET_COMMENTS_RESULT';
const POST_COMMENT_SAGA = 'app/comments/POST_COMMENT_SAGA';
const POST_COMMENT_RESULT = 'app/comments/POST_COMMENT_RESULT';

export {
  GET_COMMENTS_SAGA,
  GET_COMMENTS_RESULT,
  POST_COMMENT_SAGA,
  POST_COMMENT_RESULT,
};
