ports:
  containerPort: 8080

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 30
  timeoutSeconds: 10
  failureTheshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 30

resources:
  limits:
    cpu: "1"
    memory: 2G
  requests:
    cpu: "0.5"
    memory: 1024M

