apiVersion: v1
appVersion: 1.0
description: CMOD in K8S
name: cmodui
version: 0.1.0

tower: servicing
cloudprovider: Azure
product: cmod
appname: cmodui
register_apim: false
owner: umesh.gaddam@mrcooper.com
costcenter: 39183