host: mrcooper.io
tower: servicing
stackname: cmod
product: cmod
appname: cmodui
internal: true
api: true
os: linux
traefik_frontend_directives: "PathPrefixStrip:/cmodui/"
newrelic_appname_dynamic: false
newrelic_appname:
  dev: cmoduidev
  qa: cmoduiqa
  uat: cmoduiuat
  prod: cmoduiprod
replicas_lower: 1
replicas_upper: 3
max_mem: 1G
max_cpu: 1.0
application_internal_port: 8080
register_apim: false