const AUTO_SAVE_TRIGGER = 'app/dashboard/AUTO_SAVE_TRIGGER';
const AUTO_SAVE_OPERATIONS = 'app/dashboard/AUTO_SAVE_OPERATIONS';
const CLEAR_DISPOSITION = 'app/dashboard/CLEAR_DISPOSITION';
const CLEAR_FIRST_VISIT = 'app/dashboard/CLEAR_FIRST_VISIT';
const END_SHIFT = 'app/dashboard/END_SHIFT';
const TASKS_NOT_FOUND = 'app/dashboard/TASKS_NOT_FOUND';
const TASKS_FETCH_ERROR = 'app/dashboard/TASKS_FETCH_ERROR';
const GET_NEXT = 'app/dashboard/GET_NEXT';
const SET_EXPAND_VIEW_SAGA = 'app/dashboard/set_expand_view_saga';
const SET_EXPAND_VIEW = 'app/dashboard/SET_EXPAND_VIEW';
const SUCCESS_END_SHIFT = 'app/dashboard/SUCCESS_END_SHIFT';
const VALIDATE_DISPOSITION_SAGA = 'app/dashboard/VALIDATE_DISPOSITION_SAGA';
const SAVE_DISPOSITION_SAGA = 'app/dashboard/SAVE_DISPOSITION_SAGA';
const SAVE_DISPOSITION = 'app/dashboard/SAVE_DISPOSITION';
const SET_GET_NEXT_STATUS = 'app/dashboard/SET_GET_NEXT_STATUS';
const USER_NOTIF_MSG = 'app/dashboard/USER_NOTIF_MSG';
const SAVE_EVALID_LOANNUMBER = 'app/dashboard/SAVE_EVALID_LOANNUMBER';
const SAVE_SELECTED_DISPOSITION = 'app/dashboard/SAVE_SELECTED_DISPOSITION';
const SHOW_LOADER = 'app/dasboard/SHOW_LOADER';
const SHOW_SAVING_LOADER = 'app/dashboard/SHOW_SAVING_LOADER';
const HIDE_SAVING_LOADER = 'app/dashboard/HIDE_SAVING_LOADER';
const HIDE_LOADER = 'app/dashboard/HIDE_LOADER';
const SEARCH_LOAN_RESULT = 'app/dashboard/SEARCH_LOAN_RESULT';
const SEARCH_LOAN_TRIGGER = 'app/dashboard/SEARCH_LOAN_TRIGGER';
const UNASSIGN_LOAN = 'app/dashboard/UNASSIGN_LOAN';
const UNASSIGN_LOAN_RESULT = 'app/dashboard/UNASSIGN_LOAN_RESULT';
const ASSIGN_LOAN = 'app/dashboard/ASSIGN_LOAN';
const ASSIGN_LOAN_RESULT = 'app/dashboard/ASSIGN_LOAN_RESULT';
const HIDE_ASSIGN_UNASSIGN = 'app/dashboard/HIDE_ASSIGN_UNASSIGN';
const POST_COMMENT = 'app/dashboard/POST_COMMENT';
const CLEAR_BE_DISPOSITION = 'CLEAR_BE_DISPOSITION';
const GROUP_NAME = 'GROUP_NAME';
const SAVE_LOANNUMBER_PROCESSID = 'app/dashboard/SAVE_EVALID_LOANNUMBER';

export {
  AUTO_SAVE_TRIGGER,
  AUTO_SAVE_OPERATIONS,
  CLEAR_DISPOSITION,
  CLEAR_FIRST_VISIT,
  END_SHIFT,
  TASKS_NOT_FOUND,
  GET_NEXT,
  SET_EXPAND_VIEW,
  SET_EXPAND_VIEW_SAGA,
  VALIDATE_DISPOSITION_SAGA,
  SAVE_DISPOSITION_SAGA,
  SAVE_DISPOSITION,
  SAVE_EVALID_LOANNUMBER,
  SAVE_SELECTED_DISPOSITION,
  SHOW_SAVING_LOADER,
  HIDE_SAVING_LOADER,
  USER_NOTIF_MSG,
  TASKS_FETCH_ERROR,
  SUCCESS_END_SHIFT,
  SHOW_LOADER,
  HIDE_LOADER,
  SEARCH_LOAN_RESULT,
  SEARCH_LOAN_TRIGGER,
  UNASSIGN_LOAN,
  UNASSIGN_LOAN_RESULT,
  ASSIGN_LOAN,
  ASSIGN_LOAN_RESULT,
  HIDE_ASSIGN_UNASSIGN,
  POST_COMMENT,
  CLEAR_BE_DISPOSITION,
  GROUP_NAME,
  SAVE_LOANNUMBER_PROCESSID,
  SET_GET_NEXT_STATUS,
};
