resources:
  repositories:
    - repository: templates
      type: git
      name: 'Infrastructure Automation/AzureDevOps.Pipeline.Templates'

parameters:
  - name: dryrun
    displayName: helm --dry-run
    type: boolean
    default: false  

trigger:
  branches:
    include:
      - CMOD/SEPTEMBER
    exclude:
      - master
  paths:
    exclude:
      - secrets
        
name: Release-$(Rev:r.)

extends:
  template: k8s.yml@templates
  parameters:
    dryrun: ${{ parameters.dryrun }}
    includeDev: true
    includeQA: false
    includeUAT: false
    includeProd: false
    buildpipelineconfigurationfile: $(build.sourcesdirectory)/qaapl/deployment/Chart.yaml
    deployworkingdirectory: $(Agent.BuildDirectory)/drop/qaapl
    scanType: arbExempt