const CSIFieldsOption = [
  'ArmresetDate',
  'autoApproved',
  'autoApproveResponse',
  'calcMethod',
  'canAutomate',
  'capitalizeCurrentForbearance',
  'capitalizeFutureEscrow',
  'caseDisposableIncomeRatio',
  'caseInitiate',
  'caseInterestRate',
  'casePayment',
  'casePITI',
  'caseTI',
  'caseWAC',
  'consecutiveDelinquentMonthCount',
  'conversionType',
  'dateOfDefault',
  'daysDelinquent',
  'daysDelinquentCompletePackage',
  'declarationDate',
  'deferralCorporateAdvance',
  'deferralEscrowAdvance',
  'deferralInterest',
  'deferralPrincipal',
  'deferralType',
  'delinquentInterestAmount',
  'delinquentPI',
  'delinquentPrincipalAmount',
  'delinquentTI',
  'disposableIncome',
  'Do Not Use',
  'eligibilityType',
  'escrowed',
  'escrowMonthlyShortage',
  'escrowPaymentPending',
];

export default CSIFieldsOption;
