const GIFieldsOption = [
  'ArmresetInterestRate',
  'ArmresetPaymentAmount',
  'capEndingDueDate',
  'capEndingDueDate',
  'CapitalizedCorporateAdvances',
  'capitalizedEscrowAdvance',
  'caseInterestRate',
  'caseModifiedTerm',
  'casePayment',
  'casePITI',
  'caseStartDate',
  'caseTI',
  'conversionDisbursements',
  'currentForbearanceAmount',
  'currentInterestRate',
  'currentMaturityDate',
  'currentNextDueDate',
  'currentNextDuePI',
  'currentNextDuePITI',
  'currentNextDueTI',
  'currentPayment',
  'currentUPB',
  'Do Not Use',
  'estimatedReinstatementAmount',
  'freddieresponsedatetime',
  'interestBearingUPB',
  'interestMethod',
  'interestPaidThroughDate',
  'lastPaidInstallmentDate',
  'LockedCollateralValue',
  'LockedCurrentInterestDue',
  'LockedDelegateType',
  'LockedForbearanceAmount',
  'LockedForbearenceAmount',
  'LockedHmprate',
];

export default GIFieldsOption;
